### ISSUE TITLE
mail_template_styling not applying changes

### ISSUE THREAD

**Issue by ruifranco** [novacode-nl/odoo-addons#2]
I'm afraid that, although changes are applied when previewing an email template, they are not when actually sending the email. I have done some changes to the code and, now, I can see CSS being applied.

    # transformed by Rui Franco
    def generate_email(self, res_ids, fields=None):
        self.ensure_one()

        # Fix 1 - we must force body_html to be returned
        fields=None

        results = super(MailTemplate, self).generate_email(res_ids, fields)

        # Fix 2 - we must apply changes to all email templates
        # Fix 3 - we must get the values from the dictionary
        for key,value in results.items():
            if 'body_html' not in results[key]:
                return results

            body_html = results[key]['body_html']

            if self.strip_inline_style:
                # Just do: strip_style=True
                body_html = html_sanitize(body_html, sanitize_tags=False,
                                            sanitize_attributes=False,
                                            sanitize_style=False,
                                            strip_style=True)
            if self.print_ref:
                body_html += self._print_ref()
            if self.style_id:
                body_html = '<style type="text/css">%s</style>%s' % (self.style_id.css, body_html)
                # premailer (transform) generates inline CSS/style attributes.
                body_html = transform(body_html, allow_network=False)

            results[key]['body'] = body_html
            results[key]['body_html'] = body_html

        return results

Please take a look at this.

**Comment by bobslee** [comment]
@ruifranco could you submit a PR ? So I can easily diff, review and merge.

**Comment by ruifranco** [comment]
And so I did.
Hope it can be useful.
